title: Jaxon Dierker # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  The most significant thing I've done so far it spent 8 years of my life in the United States Army Reserves as a Motor Transport Operator (88m). 
  During that time I learned discipline, dedication, and leadership. During the time afforded to me in the Reserves, I attended Penn State, obtaining a B.S in Biochemistry and Molecular Biology. I then followed that up with an M.S. in Bioinformatics from Juniata College. To obtain my M.S. I had to become proficient in data pipeline, R for statistical analysis, Python for program creation and pipeline manipulation. Much of this was managed through a Linux/unix environment on a remote cluster.
  <br><br>
  During my free time I write, my debut novel hopefully being published before the end of 2025 with four more projects on the way. I am also exceedingly passionate about the environment and spend time when I can to advocate for a greener future when I can. I spend some weekends working to that end by volunteering with Natural Lands which is a non-profit conservation organization that focuses on preserving as much wild space in Pennsylvania as possible. 
  <br><br>
  <a href="https://www.linkedin.com/in/jaxondierker/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
